{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppziggurat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppZiggurat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppZiggurat/RcppZiggurat_{{ version }}.tar.gz
  sha256: e90f7d637ae8ff3988aaf5bbdc08a3ca99f6353ef55476a93a7a1faeca1c7e9f
  patches:
    - patches/0001-set-fixed-libs.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcppgsl                    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcppgsl
    - libblas
    - gsl
  run:
    - r-base
    - r-rcpp
    - r-rcppgsl

test:
  commands:
    - $R -e "library('RcppZiggurat')"           # [not win]
    - "\"%R%\" -e \"library('RcppZiggurat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RcppZiggurat
  license: GPL-2.0-only
  summary: The Ziggurat generator for normally distributed random numbers, originally proposed by Marsaglia and Tsang (2000,  <doi:10.18637/jss.v005.i08>) has been improved upon a few times starting with Leong et al (2005, <doi:10.18637/jss.v012.i07>). This package provides an aggregation in order to compare different implementations
    in order to provide an 'faster but good enough' alternative for use with R and C++ code.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
